version: '3.8'

services:
  dreamina-free-api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    container_name: dreamina-free-api-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Shanghai
    volumes:
      # 开发环境挂载源代码以支持热重载
      - ./src:/app/src:ro
      - ./configs:/app/configs:ro
      - ./public:/app/public:ro
      # 保护node_modules不被覆盖
      - /app/node_modules
    networks:
      - dreamina-dev-network
    command: ["npm", "run", "dev"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dreamina-dev-network:
    driver: bridge